# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"test_func": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://arampacha.github.io/nn4tab/"

git_url = "https://github.com/arampacha/nn4tab/tree/master/"

def custom_doc_links(name): return None
