# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"test_func": "00_core.ipynb",
         "cont_cat_split": "01_data.ipynb",
         "fake_data": "00a_test_utils.ipynb",
         "test_normalized": "00a_test_utils.ipynb",
         "test_nans": "00a_test_utils.ipynb",
         "test_categorical": "00a_test_utils.ipynb",
         "test_df_processed": "00a_test_utils.ipynb",
         "TabularProc": "01_data.ipynb",
         "Normalize": "01_data.ipynb",
         "FillMissing": "01_data.ipynb",
         "Categorify": "01_data.ipynb",
         "TabularDataset": "01_data.ipynb",
         "get_dsets": "01_data.ipynb",
         "get_dl": "01_data.ipynb",
         "noop": "02_model.ipynb",
         "LinearBlock": "02_model.ipynb",
         "trunc_normal_": "02_model.ipynb",
         "Embedding": "02_model.ipynb",
         "TabInputBlock": "02_model.ipynb",
         "TabularModel": "02_model.ipynb",
         "get_tabular_model": "02_model.ipynb",
         "emb_sz_rule": "02_model.ipynb",
         "emb_sizes": "02_model.ipynb",
         "AverageMeter": "03_learner.ipynb",
         "accuracy_binary": "03_learner.ipynb",
         "Callback": "03_learner.ipynb",
         "LearnerV0": "03_learner.ipynb"}

modules = ["core.py",
           "test_utils.py",
           "data.py",
           "model.py",
           "learner.py"]

doc_url = "https://arampacha.github.io/nn4tab/"

git_url = "https://github.com/arampacha/nn4tab/tree/master/"

def custom_doc_links(name): return None
